name: Rolling Release

on:
  push:
    branches:
      - main

# Only allow one main build & deployment at a time
concurrency: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker / Login (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker / Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker / Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/nilathedragon/spamscale:latest
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
